import React from "react";
import { GlassCard } from "@/components/ui/GlassCard";
import { APP_CONFIG } from "@/config/app.config";
import { FileText, Shield } from "lucide-react";

export default function TermsPage() {
  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 py-12 space-y-6">
      <div className="flex items-center gap-3">
        <div className="p-2.5 rounded-xl bg-violet-600/20 text-violet-400">
          <FileText className="w-6 h-6" />
        </div>
        <div>
          <h1 className="text-2xl font-black text-white">Terms of Service & Rules</h1>
          <p className="text-xs text-slate-400">Last updated: October 2026</p>
        </div>
      </div>

      <GlassCard className="p-8 space-y-6 text-xs text-slate-300 leading-relaxed">
        <section className="space-y-2">
          <h2 className="text-sm font-bold text-white uppercase tracking-wider text-cyan-400">
            1. Eligibility & Age Restriction
          </h2>
          <p>
            You must be at least 18 years of age to register an account or participate in tournaments on {APP_CONFIG.brand.name}. By participating in real-money contests, you represent that you are a resident of India and not located in restricted jurisdictions (Assam, Odisha, Telangana, Nagaland, Andhra Pradesh, and Sikkim).
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-sm font-bold text-white uppercase tracking-wider text-cyan-400">
            2. Platform Nature & Trademarks
          </h2>
          <p>
            {APP_CONFIG.brand.name} is an independent esports competition organizer. We are not affiliated with, endorsed by, or sponsored by any third-party mobile games or trademark owners. Matches are played externally using standard room codes generated by players or room hosts.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-sm font-bold text-white uppercase tracking-wider text-cyan-400">
            3. Fair Play & Screenshot Verification
          </h2>
          <p>
            Participants are required to submit unmodified, original screenshots of the end-game score screen. The submission of edited, forged, or reused screenshots constitutes fraud, resulting in permanent account termination, forfeiture of balances, and reporting to relevant anti-fraud authorities.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-sm font-bold text-white uppercase tracking-wider text-cyan-400">
            4. Wallet Balances & Escrow
          </h2>
          <p>
            All entry fees are debited into a secure escrow hold upon registration. Prize payouts are credited to Withdrawable Winnings Balances upon verified match conclusion minus the {APP_CONFIG.features.platformFeePercent}% organizer service commission.
          </p>
        </section>
      </GlassCard>
    </div>
  );
}
